# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 320)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 9, 481, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l1.setObjectName("l1")
        self.verticalLayout.addWidget(self.l1)
        self.V1 = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.V1.setObjectName("V1")
        self.verticalLayout.addWidget(self.V1)
        self.l2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l2.setObjectName("l2")
        self.verticalLayout.addWidget(self.l2)
        self.V2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.V2.setObjectName("V2")
        self.verticalLayout.addWidget(self.V2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 170, 481, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.B_AC = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.B_AC.setObjectName("B_AC")
        self.horizontalLayout.addWidget(self.B_AC)
        self.B_X = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.B_X.setObjectName("B_X")
        self.horizontalLayout.addWidget(self.B_X)
        self.B_Y = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.B_Y.setObjectName("B_Y")
        self.horizontalLayout.addWidget(self.B_Y)
        self.B_C1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.B_C1.setObjectName("B_C1")
        self.horizontalLayout.addWidget(self.B_C1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 200, 481, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.B_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.B_1.setObjectName("B_1")
        self.horizontalLayout_2.addWidget(self.B_1)
        self.B_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.B_2.setObjectName("B_2")
        self.horizontalLayout_2.addWidget(self.B_2)
        self.B_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.B_3.setObjectName("B_3")
        self.horizontalLayout_2.addWidget(self.B_3)
        self.B_C2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.B_C2.setObjectName("B_C2")
        self.horizontalLayout_2.addWidget(self.B_C2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(-1, 230, 481, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.B_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.B_4.setObjectName("B_4")
        self.horizontalLayout_3.addWidget(self.B_4)
        self.B_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.B_5.setObjectName("B_5")
        self.horizontalLayout_3.addWidget(self.B_5)
        self.B_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.B_6.setObjectName("B_6")
        self.horizontalLayout_3.addWidget(self.B_6)
        self.B_J1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.B_J1.setObjectName("B_J1")
        self.horizontalLayout_3.addWidget(self.B_J1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 260, 481, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.B_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.B_7.setObjectName("B_7")
        self.horizontalLayout_4.addWidget(self.B_7)
        self.B_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.B_8.setObjectName("B_8")
        self.horizontalLayout_4.addWidget(self.B_8)
        self.B_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.B_9.setObjectName("B_9")
        self.horizontalLayout_4.addWidget(self.B_9)
        self.B_J2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.B_J2.setObjectName("B_J2")
        self.horizontalLayout_4.addWidget(self.B_J2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(-1, 290, 481, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.B_000 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.B_000.setObjectName("B_000")
        self.horizontalLayout_5.addWidget(self.B_000)
        self.B_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.B_0.setObjectName("B_0")
        self.horizontalLayout_5.addWidget(self.B_0)
        self.B_P = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.B_P.setObjectName("B_P")
        self.horizontalLayout_5.addWidget(self.B_P)
        self.B_D = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.B_D.setObjectName("B_D")
        self.horizontalLayout_5.addWidget(self.B_D)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "计算器"))
        self.l1.setText(_translate("Form", "计算式："))
        self.l2.setText(_translate("Form", "结果："))
        self.B_AC.setText(_translate("Form", "AC"))
        self.B_X.setText(_translate("Form", "<-"))
        self.B_Y.setText(_translate("Form", "%"))
        self.B_C1.setText(_translate("Form", "/"))
        self.B_1.setText(_translate("Form", "1"))
        self.B_2.setText(_translate("Form", "2"))
        self.B_3.setText(_translate("Form", "3"))
        self.B_C2.setText(_translate("Form", "*"))
        self.B_4.setText(_translate("Form", "4"))
        self.B_5.setText(_translate("Form", "5"))
        self.B_6.setText(_translate("Form", "6"))
        self.B_J1.setText(_translate("Form", "-"))
        self.B_7.setText(_translate("Form", "7"))
        self.B_8.setText(_translate("Form", "8"))
        self.B_9.setText(_translate("Form", "9"))
        self.B_J2.setText(_translate("Form", "+"))
        self.B_000.setText(_translate("Form", "000"))
        self.B_0.setText(_translate("Form", "0"))
        self.B_P.setText(_translate("Form", "."))
        self.B_D.setText(_translate("Form", "="))
